const $ = id => document.getElementById(id);
const money = value => new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 0 }).format(Math.round(value));
const pct = value => `${value.toFixed(2).replace('.', ',')}%`;
const typeNames = { strip: 'ленты', rewind: 'рулона', sheet: 'листа', card: 'карточки' };
let selectedType = 'strip';

// Прайсы Ferrit от 01.03.2026. Все цены включают НДС.
const PRICE = {
  crossCut: { full: 4660, partial: 7032, open: 4060, minTons: 2, special: 1000 },
  longitudinal: {
    minTons: 3, special: 500, minScrap: 8, followUpDiscount: 500,
    standard: { '>30': { full: 4179, partial: 6368, open: 3460 }, '19-30': { full: 7112, partial: 11038, open: 5920 }, '12-18.9': { full: 10221, partial: 15948, open: 8250 }, '5-11.9': { full: 15131, partial: 22577, open: 11960 } },
    narrow: { '>30': { full: 4328, partial: 6667, open: 3460 }, '19-30': { full: 7397, partial: 11528, open: 5920 }, '12-18.9': { full: 10221, partial: 15948, open: 8250 }, '5-11.9': { full: 15131, partial: 22577, open: 11960 } }
  },
  rewind: { full: 4010, partial: 6165, open: 3460, narrowThin: { full: 4083, partial: 6372, open: 3460 }, minTons: 3 },
  grinding: { rollMinTons: 3, sheetMinTons: 1, roll: [{ max: .6, partial: 11790 }, { max: .8, partial: 10071 }, { max: 1, partial: 8962 }, { max: 1.5, partial: 8242 }, { max: 3, partial: 7687 }, { max: 5, partial: 7022 }], sheet: 10900, rewind: { full: 3760, partial: 5772, open: 3183 } },
  film: { roll: 1600, sheet: [{ max: 1.5, price: 6400 }, { max: 5, price: 4400 }] }, density: 7.8
};
const COIL_WIDTHS = [1000, 1250, 1500];
const getRadio = name => document.querySelector(`input[name="${name}"]:checked`).value;
const charge = (rate, volume, minTons) => rate * Math.max(volume, minTons) / volume;

function showStep(step) { $('typeStep').hidden = step !== 1; $('paramsStep').hidden = step !== 2; $('resultsStep').hidden = step !== 3; ['step1Nav', 'step2Nav', 'step3Nav'].forEach((id, i) => $(id).classList.toggle('active', i + 1 === step)); }
function updateUnits() { const count = selectedType === 'sheet' || selectedType === 'card'; document.querySelector('.unit-count').hidden = !count; document.querySelector('.unit-meters').hidden = count; $('unitLegend').textContent = 'Единица заказа'; if ((count && getRadio('unit') === 'meters') || (!count && getRadio('unit') === 'pieces')) document.querySelector('input[name="unit"][value="tons"]').checked = true; }
function setType(type) { selectedType = type; document.querySelectorAll('.type-card').forEach(card => card.classList.toggle('selected', card.dataset.type === type)); $('paramsTitle').textContent = `Параметры ${typeNames[type]}`; document.querySelector('.length-field').hidden = type === 'strip' || type === 'rewind'; $('productWidthLabel').firstChild.textContent = type === 'rewind' ? 'Ширина рулона, мм' : 'Ширина готового изделия, мм'; updateUnits(); }
function thicknessBand(t) { return t <= .6 ? 0 : t <= .8 ? 1 : t <= 1 ? 2 : t <= 1.5 ? 3 : t <= 3 ? 4 : t <= 5 ? 5 : -1; }
function grindingPrice(type, thickness, volume) { if (type === 'sheet') return charge(PRICE.grinding.sheet, volume, PRICE.grinding.sheetMinTons); const band = PRICE.grinding.roll[thicknessBand(thickness)]; return band ? charge(band.partial, volume, PRICE.grinding.rollMinTons) : 0; }
function filmPrice(type, thickness, yieldRate) { if (getRadio('film') === 'none') return 0; const sides = getRadio('filmSides') === 'two' ? 2 : 1; const sourceWidthFactor = 1 / Math.max(yieldRate, 0.000001); if (type === 'strip' || type === 'rewind' || type === 'card') return PRICE.film.roll * sides * sourceWidthFactor; const band = PRICE.film.sheet.find(item => thickness <= item.max); return band ? band.price * sides * sourceWidthFactor : 0; }
function stripBand(width) { return width > 30 ? '>30' : width >= 19 ? '19-30' : width >= 12 ? '12-18.9' : '5-11.9'; }
function maxStrips(thickness, coilWidth) { const band = thickness <= .6 ? 0 : thickness <= .8 ? 1 : thickness <= 1 ? 2 : thickness <= 1.2 ? 3 : thickness <= 1.5 ? 4 : 5; const limits = coilWidth < 500 ? [15, 15, 13, 13, 0, 7] : coilWidth < 1000 ? [16, 16, 13, 13, 0, 7] : [25, 21, 20, 17, 15, 10]; return limits[band] || 0; }
function longitudinalRate(width, mode, coilWidth) { const table = coilWidth < 500 || width < 20 ? PRICE.longitudinal.narrow : PRICE.longitudinal.standard; return table[stripBand(width)]?.[mode] || 0; }
function quantityToTons(quantity, unit, thickness, width, length) { if (unit === 'tons') return quantity; if (unit === 'meters') return quantity * thickness * width * PRICE.density * 0.0000078; return quantity * thickness * (width / 1000) * (length / 1000) * PRICE.density / 1000; }

function serviceData(coilWidth, productWidth, thickness, volume, price, cardSize = '') {
  const laneWidths = Array.isArray(productWidth) ? productWidth : [productWidth], usedWidth = laneWidths.reduce((sum, width) => sum + width, 0), pieces = selectedType === 'rewind' ? 1 : laneWidths.length, scrap = coilWidth - usedWidth, yieldRate = usedWidth / coilWidth;
  if (!pieces || (selectedType !== 'sheet' && selectedType !== 'rewind' && maxStrips(thickness, coilWidth) < pieces) || (selectedType !== 'sheet' && selectedType !== 'rewind' && scrap > 0 && scrap < PRICE.longitudinal.minScrap)) return null;
  const mode = scrap === 0 ? 'full' : 'partial', operations = [], hasGrinding = getRadio('surface') === '4n';
  let firstCut = 0;
  let grinding = 0; if (hasGrinding) { grinding = grindingPrice(selectedType, thickness, volume); operations.push({ name: '1. Шлифовка 4N', mode: mode === 'full' ? 'полный рулон' : 'частичный рулон', price: grinding }); if (getRadio('film') !== 'none' && getRadio('filmSides') === 'two') { const rewindPrice = PRICE.grinding.rewind[mode]; operations.push({ name: 'Дополнительная перемотка на шлифовке', mode: 'вторая сторона', price: charge(rewindPrice, volume, selectedType === 'sheet' ? 1 : PRICE.grinding.rollMinTons) }); } }
  if (selectedType === 'strip' || selectedType === 'card') { const cutMode = hasGrinding ? 'open' : mode, tariffWidth = Math.max(...laneWidths); firstCut = longitudinalRate(tariffWidth, cutMode, coilWidth); if (!firstCut) return null; firstCut = charge(firstCut, volume, PRICE.longitudinal.minTons); if ($('specialConditions').checked) firstCut += PRICE.longitudinal.special; if ($('furtherProcessing').checked) firstCut = Math.max(0, firstCut - PRICE.longitudinal.followUpDiscount); operations.push({ name: selectedType === 'card' ? (hasGrinding ? '2. Продольная резка в ленту' : '1. Продольная резка в ленту') : hasGrinding ? '2. Продольная резка в ленту' : '1. Продольная резка в ленту', mode: cutMode === 'open' ? 'открытый рулон до конца' : cutMode === 'full' ? 'полный рулон' : 'частичный рулон', price: firstCut }); }
  if (selectedType === 'rewind') { const tariff = thickness <= .4 ? PRICE.rewind.narrowThin : PRICE.rewind, rewindMode = hasGrinding ? 'open' : mode; firstCut = charge(tariff[rewindMode], volume, PRICE.rewind.minTons); if ($('specialConditions').checked) firstCut += PRICE.longitudinal.special; operations.push({ name: hasGrinding ? '2. Перемотка рулона' : '1. Перемотка рулона', mode: rewindMode === 'open' ? 'открытый рулон до конца' : rewindMode === 'full' ? 'полный рулон' : 'частичный рулон', price: firstCut }); }
  let secondCut = 0; if (selectedType === 'sheet' || selectedType === 'card') { const cutMode = hasGrinding || selectedType === 'card' ? 'open' : mode; secondCut = charge(PRICE.crossCut[cutMode], volume, PRICE.crossCut.minTons); if ($('specialConditions').checked) secondCut += PRICE.crossCut.special; if ($('noPallet').checked) secondCut = Math.max(0, secondCut - 500); operations.push({ name: selectedType === 'card' ? '3. Поперечная резка в карточки' : hasGrinding ? '2. Поперечная резка в лист' : '1. Поперечная резка в лист', mode: cutMode === 'open' ? 'открытый рулон до конца' : cutMode === 'full' ? 'полный рулон' : 'частичный рулон', price: secondCut }); } else if ($('noPallet').checked) firstCut = Math.max(0, firstCut - 500);
  const film = filmPrice(selectedType, thickness, yieldRate); if (film) operations.push({ name: 'Плёнка', mode: getRadio('filmSides') === 'two' ? 'с двух сторон' : 'с одной стороны', price: film });
  const materialCost = Number($('materialCost').value), effectiveMaterial = materialCost / yieldRate, scrapCost = materialCost * (1 - yieldRate) / yieldRate, processing = operations.reduce((sum, item) => sum + item.price, 0);
  return { coilWidth, pieces, scrap, yieldRate, price, cardSize, effectiveMaterial, scrapCost, cutting: firstCut + secondCut, firstCut, secondCut, grinding, film, processing, total: price + processing + scrapCost, mode, operations };
}

function cardLayouts(coilWidth, firstWidth, secondWidth, thickness) {
  const layouts = [], max = maxStrips(thickness, coilWidth), duplicate = firstWidth === secondWidth;
  for (let first = 0; first <= max; first += 1) for (let second = 0; second <= max - first; second += 1) {
    if (!first && !second) continue;
    if (duplicate && second) continue;
    const widths = [...Array(first).fill(firstWidth), ...Array(second).fill(secondWidth)], used = widths.reduce((sum, width) => sum + width, 0), scrap = coilWidth - used;
    if (used <= coilWidth && (scrap === 0 || scrap >= PRICE.longitudinal.minScrap)) {
      const label = `${first ? `${first}×${firstWidth} мм` : ''}${first && second ? ' + ' : ''}${second ? `${second}×${secondWidth} мм` : ''}`;
      layouts.push({ widths, label });
    }
  }
  return layouts;
}

function stripLayouts(coilWidth, stripWidth, thickness) {
  const layouts = [], max = Math.min(maxStrips(thickness, coilWidth), Math.floor(coilWidth / stripWidth));
  for (let count = 1; count <= max; count += 1) {
    const used = count * stripWidth, scrap = coilWidth - used;
    if (scrap === 0 || scrap >= PRICE.longitudinal.minScrap) layouts.push({ widths: Array(count).fill(stripWidth), label: `${count}×${stripWidth} мм` });
  }
  return layouts;
}

function calculate() {
  const thickness = Number($('thickness').value), productWidth = Number($('productWidth').value), length = Number($('productLength').value) || 0, quantity = Number($('quantity').value), materialCost = Number($('materialCost').value), price = Number($('price').value), unit = getRadio('unit'), error = $('error'), film = getRadio('film'), filmSides = getRadio('filmSides');
  if (![thickness, productWidth, quantity, materialCost, price].every(Number.isFinite) || thickness <= 0 || productWidth <= 0 || quantity <= 0 || materialCost < 0 || price < 0 || (selectedType !== 'strip' && selectedType !== 'rewind' && length <= 0) || (filmSides === 'two' && (film === 'none' || thickness > 2))) { error.textContent = filmSides === 'two' && film === 'none' ? 'Для двухсторонней плёнки выберите PE или LPE.' : filmSides === 'two' && thickness > 2 ? 'Плёнка с двух сторон доступна только до толщины 2,0 мм.' : 'Проверьте заполнение параметров.'; error.hidden = false; return; }
  const volume = quantityToTons(quantity, unit, thickness, productWidth, length); if (!Number.isFinite(volume) || volume <= 0) { error.textContent = 'Не удалось перевести количество в тонны. Проверьте размеры.'; error.hidden = false; return; } error.hidden = true;
  const candidates = selectedType === 'sheet' || selectedType === 'rewind' ? [productWidth] : COIL_WIDTHS;
  const rows = (selectedType === 'card' ? candidates.flatMap(width => cardLayouts(width, productWidth, length, thickness).map(layout => serviceData(width, layout.widths, thickness, volume, price, layout.label))) : selectedType === 'strip' ? candidates.flatMap(width => stripLayouts(width, productWidth, thickness).map(layout => serviceData(width, layout.widths, thickness, volume, price, layout.label))) : candidates.map(width => serviceData(width, productWidth, thickness, volume, price))).filter(Boolean).sort((a, b) => a.total - b.total).slice(0, 5); if (!rows.length) { error.textContent = 'По условиям прайса подходящего варианта нет: проверьте ширину, толщину, количество полос и откройник.'; error.hidden = false; return; }
  $('resultCaption').textContent = `${typeNames[selectedType][0].toUpperCase() + typeNames[selectedType].slice(1)}: ${productWidth} мм${selectedType !== 'strip' && selectedType !== 'rewind' ? ` × ${length} мм` : ''} · задано ${quantity} ${unit === 'tons' ? 'т' : unit === 'meters' ? 'м' : 'шт'} (${volume.toFixed(3).replace('.', ',')} т)`;
  const best = rows[0]; document.querySelectorAll('.scrap-col,.scrap-cell').forEach(el => el.hidden = selectedType === 'sheet' || selectedType === 'rewind'); document.querySelectorAll('.orientation-col,.orientation-cell').forEach(el => el.hidden = selectedType !== 'card'); $('recommendation').innerHTML = `Рекомендуемый рулон: <strong>${best.coilWidth} мм</strong>${selectedType === 'card' && best.cardSize ? ` · раскрой ${best.cardSize}` : ''}<span>Маршрут: ${best.operations.map(item => item.name.replace(/^\d\. /, '')).join(' → ')}</span>`;
  $('resultsBody').innerHTML = rows.map((row, index) => `<tr class="${index === 0 ? 'best' : ''}"><td><strong>${row.coilWidth} мм</strong>${index === 0 ? '<em>лучший</em>' : ''}</td><td class="orientation-cell">${row.cardSize}</td><td>${row.pieces}</td><td class="scrap-cell">${row.scrap} мм / ${pct((1 - row.yieldRate) * 100)}</td><td>${pct(row.yieldRate * 100)}</td><td><strong>${money(row.total)} ₽/т</strong></td></tr>`).join('');
  const operationLines = best.operations.map(operation => `<div class="subline"><span>${operation.name}${operation.name === 'Плёнка' ? '' : ` <small>(${operation.mode})</small>`}</span><strong>${money(operation.price)} ₽/т</strong></div>`).join(''); $('priceBreakdown').innerHTML = `<h3>Итоговая цена: ${money(best.total)} ₽/т с НДС</h3><div class="price-lines"><div><span>Прайс</span><strong>${money(best.price)} ₽/т</strong></div><div><span>Переработка</span><strong>${money(best.processing)} ₽/т</strong></div>${operationLines}<div><span>Откройник от себестоимости</span><strong>${best.scrapCost ? money(best.scrapCost) + ' ₽/т' : '—'}</strong></div><div class="grand"><span>ИТОГО</span><strong>${money(best.total)} ₽/т</strong></div></div>`;
  $('note').textContent = selectedType === 'card' && getRadio('surface') === '4n' ? 'Карточки: сначала шлифовка, затем продольная резка в ленту и поперечная резка открытого рулона до конца.' : selectedType === 'card' ? 'Карточки: сначала продольная резка в ленту, затем поперечная резка открытого рулона до конца.' : selectedType === 'sheet' && getRadio('surface') === '4n' ? 'Шлифованный лист: сначала шлифовка, затем поперечная резка открытого рулона до конца.' : selectedType === 'rewind' ? 'Рулон рассчитан как отдельная операция перемотки без продольного раскроя.' : 'Автоматически применены условия прайса по режиму рулона, минимальному объёму и дальнейшей переработке.';
  const custom = document.createElement('tr'); custom.className = 'custom-row'; custom.innerHTML = `<td><input id="customCoilWidth" type="number" min="${productWidth}" step="1" placeholder="Своя ширина"></td><td class="orientation-cell"${selectedType === 'card' ? '' : ' hidden'}>${selectedType === 'card' ? 'Ориентация задаётся в таблице' : ''}</td><td colspan="${selectedType === 'sheet' || selectedType === 'rewind' ? 3 : 4}" id="customResult">Введите ширину — расчёт появится автоматически</td>`; $('resultsBody').appendChild(custom); $('customCoilWidth').addEventListener('input', () => renderCustom(Number($('customCoilWidth').value), thickness, productWidth, volume, price));
  localStorage.setItem('metal-cutter-values', JSON.stringify({ type: selectedType, thickness, productWidth, length, quantity, unit, volume, materialCost, price, surface: getRadio('surface'), film, filmSides, special: $('specialConditions').checked, further: $('furtherProcessing').checked, noPallet: $('noPallet').checked }));
}
function renderCustom(coilWidth, thickness, productWidth, volume, price) { const out = $('customResult'); if (!coilWidth || coilWidth < productWidth) { out.textContent = 'Введите ширину не меньше ширины изделия'; return; } const layout = selectedType === 'strip' ? stripLayouts(coilWidth, productWidth, thickness).at(-1) : null, row = serviceData(coilWidth, layout ? layout.widths : productWidth, thickness, volume, price, layout?.label || ''); if (!row) { out.textContent = 'Вариант не проходит по условиям прайса или минимальному откройнику'; return; } out.innerHTML = `${coilWidth} мм · ${row.pieces} полос / листов${selectedType === 'sheet' || selectedType === 'rewind' ? '' : ` · откройник <strong>${row.scrap} мм</strong>`} · переработка ${money(row.processing)} ₽/т · откройник от себестоимости ${money(row.scrapCost)} ₽/т · <strong>${money(row.total)} ₽/т</strong>`; }
document.querySelectorAll('.type-card').forEach(card => card.addEventListener('click', () => setType(card.dataset.type))); $('nextButton').addEventListener('click', () => showStep(2)); $('backButton').addEventListener('click', () => showStep(1)); $('calculateButton').addEventListener('click', () => { calculate(); if (!$('error').hidden) return; showStep(3); }); $('editButton').addEventListener('click', () => showStep(2)); $('resetButton').addEventListener('click', () => { localStorage.removeItem('metal-cutter-values'); location.reload(); });
try { const saved = JSON.parse(localStorage.getItem('metal-cutter-values') || 'null'); if (saved) { setType(saved.type || 'strip'); ['thickness', 'productWidth', 'productLength', 'quantity', 'materialCost', 'price'].forEach(id => { if (saved[id] !== undefined) $(id).value = saved[id]; }); document.querySelector(`input[name="unit"][value="${saved.unit}"]`)?.click(); document.querySelector(`input[name="surface"][value="${saved.surface}"]`)?.click(); document.querySelector(`input[name="film"][value="${saved.film}"]`)?.click(); document.querySelector(`input[name="filmSides"][value="${saved.filmSides}"]`)?.click(); $('specialConditions').checked = !!saved.special; $('furtherProcessing').checked = !!saved.further; $('noPallet').checked = !!saved.noPallet; } } catch {} setType(selectedType); showStep(1);
