const $ = id => document.getElementById(id);
const money = value => new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 0 }).format(Math.round(value));
const decimal = value => new Intl.NumberFormat('ru-RU', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(Number(String(value).replace(',', '.')));
const prettyLayout = value => String(value || '').replace(/(\d+(?:[.,]\d+)?)(?= мм)/g, value => decimal(value));
const pct = value => `${value.toFixed(2).replace('.', ',')}%`;
const typeNames = { strip: 'ленты', rewind: 'рулона', sheet: 'листа', card: 'карточки' };
let selectedType = 'strip';

// Прайсы Ferrit от 01.03.2026. Все цены включают НДС.
const PRICE = {
  crossCut: { full: 4660, partial: 7032, open: 4060, minTons: 2, special: 1000 },
  longitudinal: {
    minTons: 3, special: 500, minScrap: 6, followUpDiscount: 500,
    standard: { '>30': { full: 4179, partial: 6368, open: 3460 }, '19-30': { full: 7112, partial: 11038, open: 5920 }, '12-18.9': { full: 10221, partial: 15948, open: 8250 }, '5-11.9': { full: 15131, partial: 22577, open: 11960 } },
    narrow: { '>30': { full: 4328, partial: 6667, open: 3460 }, '19-30': { full: 7397, partial: 11528, open: 5920 }, '12-18.9': { full: 10221, partial: 15948, open: 8250 }, '5-11.9': { full: 15131, partial: 22577, open: 11960 } }
  },
  rewind: { full: 4010, partial: 6165, open: 3460, narrowThin: { full: 4083, partial: 6372, open: 3460 }, minTons: 3 },
  grinding: { rollMinTons: 3, sheetMinTons: 1, roll: [{ max: .6, full: 8901, partial: 11790, open: 8254 }, { max: .8, full: 7469, partial: 10071, open: 6822 }, { max: 1, full: 6545, partial: 8962, open: 5898 }, { max: 1.5, full: 5944, partial: 8242, open: 5297 }, { max: 3, full: 5482, partial: 7687, open: 4835 }, { max: 5, full: 4928, partial: 7022, open: 4281 }], sheet: 10900, rewind: { full: 3760, partial: 5772, open: 3183 } },
  film: { roll: 1600, sheet: [{ max: 1.5, price: 6400 }, { max: 5, price: 4400 }] }, density: 7.8
};
const COIL_WIDTHS = [1000, 1250, 1500];
const getRadio = name => document.querySelector(`input[name="${name}"]:checked`).value;
const charge = (rate, volume, minTons, mode) => rate * (mode === 'open' ? volume : Math.max(volume, minTons)) / volume;

function showStep(step) { $('typeStep').hidden = step !== 1; $('paramsStep').hidden = step !== 2; $('resultsStep').hidden = step !== 3; ['step1Nav', 'step2Nav', 'step3Nav'].forEach((id, i) => $(id).classList.toggle('active', i + 1 === step)); }
function updateUnits() { const count = selectedType === 'sheet' || selectedType === 'card'; document.querySelectorAll('.unit-count').forEach(el => { el.hidden = !count; el.style.display = count ? '' : 'none'; }); document.querySelectorAll('.unit-meters').forEach(el => { el.hidden = count; el.style.display = count ? 'none' : ''; }); $('unitLegend').textContent = 'Единица заказа'; if ((count && getRadio('unit') === 'meters') || (!count && getRadio('unit') === 'pieces')) document.querySelector('input[name="unit"][value="tons"]').checked = true; }
function addOpenModeField() { const conditions = document.querySelector('.conditions'); if (!conditions || document.querySelector('input[name="openMode"]')) return; const row = document.createElement('div'); row.className = 'choice-row open-mode-row'; row.innerHTML = '<fieldset><legend>Рулон</legend><label class="radio"><input name="openMode" value="partial" type="radio" checked> Частично</label><label class="radio"><input name="openMode" value="full" type="radio"> Полностью</label><label class="radio"><input name="openMode" value="open" type="radio"> Полностью открытый</label></fieldset>'; conditions.before(row); }
function updateRewindWidthControl() { const label = $('productWidthLabel'), current = $('productWidth'); if (selectedType === 'rewind' && current?.tagName !== 'SELECT') { const select = document.createElement('select'); select.id = 'productWidth'; select.innerHTML = [1000, 1219, 1250, 1500].map(width => `<option value="${width}">${width} мм</option>`).join(''); select.value = [1000, 1219, 1250, 1500].includes(Number(current?.value)) ? current.value : '1250'; current?.replaceWith(select); } else if (selectedType !== 'rewind' && current?.tagName === 'SELECT') { const input = document.createElement('input'); input.id = 'productWidth'; input.type = 'number'; input.min = '1'; input.step = '1'; input.value = current.value || '125'; current.replaceWith(input); } label.firstChild.textContent = selectedType === 'rewind' ? 'Ширина рулона, мм' : 'Ширина готового изделия, мм'; }
function updateStripSizeControl() { const label = $('productWidthLabel'), current = $('productWidth'), quantityLabel = $('quantity')?.closest('label'), fieldGrid = document.querySelector('.field-grid'); if (!label || selectedType !== 'strip') { label?.querySelector('.strip-size-mode')?.remove(); document.querySelector('.multi-strip-orders')?.remove(); if (quantityLabel) quantityLabel.hidden = false; if (current?.type === 'text') { const input = document.createElement('input'); input.id = 'productWidth'; input.type = 'number'; input.min = '1'; input.step = '1'; input.value = readStripWidths(current.value)[0] || '125'; current.replaceWith(input); } return; } if (current?.type !== 'text') { const input = document.createElement('input'); input.id = 'productWidth'; input.type = 'text'; input.inputMode = 'decimal'; input.value = current?.value || '125'; current?.replaceWith(input); } if (!label.querySelector('.strip-size-mode')) { const mode = document.createElement('div'); mode.className = 'strip-size-mode'; mode.innerHTML = '<label class="radio"><input name="stripSizeMode" value="single" type="radio" checked> 1 типоразмер</label><label class="radio"><input name="stripSizeMode" value="multiple" type="radio"> Несколько типоразмеров</label>'; label.insertBefore(mode, $('productWidth')); mode.querySelectorAll('input').forEach(input => input.addEventListener('change', () => updateStripSizeControl())); } const multiple = getRadio('stripSizeMode') === 'multiple'; label.firstChild.textContent = multiple ? 'Ширины лент, мм' : 'Ширина готового изделия, мм'; label.hidden = multiple; if (quantityLabel) quantityLabel.hidden = multiple; $('productWidth').placeholder = ''; if (!fieldGrid) return; let ordersBox = document.querySelector('.multi-strip-orders'); if (!ordersBox) { ordersBox = document.createElement('div'); ordersBox.className = 'multi-strip-orders'; fieldGrid.after(ordersBox); } ordersBox.hidden = !multiple; if (!multiple) return; if (!ordersBox.querySelector('.multi-strip-row')) { const initialWidth = Number($('productWidth').value) || 125, initialQuantity = Number($('quantity').value) || 1; ordersBox.innerHTML = `<div class="multi-strip-heading"><strong>Типоразмеры и объём заказа</strong><span>Для каждой ширины укажите нужный вес или метраж</span></div><div class="multi-strip-rows"></div><button class="button ghost multi-strip-add" type="button">+ Добавить типоразмер</button>`; const rows = ordersBox.querySelector('.multi-strip-rows'); addStripOrderRow(rows, initialWidth, initialQuantity); ordersBox.querySelector('.multi-strip-add').addEventListener('click', () => addStripOrderRow(rows, '', '')); } }
function addStripOrderRow(container, width = '', quantity = '') { const row = document.createElement('div'); row.className = 'multi-strip-row'; row.innerHTML = `<label>Ширина, мм<input class="multi-strip-width" type="number" min="1" step="1" value="${width}" placeholder="Например, 163"></label><label>Количество<input class="multi-strip-quantity" type="number" min="0.001" step="0.001" value="${quantity}" placeholder="Вес или метры"></label><button class="button ghost multi-strip-remove" type="button" aria-label="Удалить типоразмер">×</button>`; row.querySelector('.multi-strip-remove').addEventListener('click', () => { if (container.children.length > 1) row.remove(); }); container.appendChild(row); }
function readStripOrders() { return [...document.querySelectorAll('.multi-strip-row')].map(row => ({ width: Number(row.querySelector('.multi-strip-width')?.value), quantity: Number(row.querySelector('.multi-strip-quantity')?.value) })).filter(order => Number.isFinite(order.width) && order.width > 0 && Number.isFinite(order.quantity) && order.quantity > 0); }
function stripLayoutScore(layout, orders) { const desired = new Map(); orders.forEach(order => desired.set(order.width, (desired.get(order.width) || 0) + order.quantity)); const desiredTotal = [...desired.values()].reduce((sum, value) => sum + value, 0); const used = layout.widths.reduce((sum, width) => sum + width, 0); return [...desired.entries()].reduce((score, [width, amount]) => score + Math.abs(amount / desiredTotal - layout.widths.filter(item => item === width).reduce((sum, item) => sum + item, 0) / used), 0); }
function setType(type) { selectedType = type; addOpenModeField(); updateRewindWidthControl(); document.querySelectorAll('label').forEach(label => { if (label.firstChild) label.firstChild.textContent = label.firstChild.textContent.replace(/руб\/т(?!н)/, 'руб/тн'); }); document.querySelectorAll('.type-card').forEach(card => card.classList.toggle('selected', card.dataset.type === type)); $('paramsTitle').textContent = `Параметры ${typeNames[type]}`; document.querySelector('.length-field').hidden = type === 'strip' || type === 'rewind'; updateStripSizeControl(); updateUnits(); }
function thicknessBand(t) { return t <= .6 ? 0 : t <= .8 ? 1 : t <= 1 ? 2 : t <= 1.5 ? 3 : t <= 3 ? 4 : t <= 5 ? 5 : -1; }
function grindingPrice(type, thickness, volume, mode) { if (type === 'sheet') return charge(PRICE.grinding.sheet, volume, PRICE.grinding.sheetMinTons); const band = PRICE.grinding.roll[thicknessBand(thickness)]; return band ? charge(band[mode], volume, PRICE.grinding.rollMinTons, mode) : 0; }
function filmPrice(type, thickness, yieldRate) { if (getRadio('film') === 'none') return 0; const sides = getRadio('filmSides') === 'two' ? 2 : 1; const sourceWidthFactor = 1 / Math.max(yieldRate, 0.000001); if (type === 'strip' || type === 'rewind' || type === 'card') return PRICE.film.roll * sides * sourceWidthFactor; const band = PRICE.film.sheet.find(item => thickness <= item.max); return band ? band.price * sides * sourceWidthFactor : 0; }
function stripBand(width) { return width > 30 ? '>30' : width >= 19 ? '19-30' : width >= 12 ? '12-18.9' : '5-11.9'; }
function maxStrips(thickness, coilWidth) { const band = thickness <= .6 ? 0 : thickness <= .8 ? 1 : thickness <= 1 ? 2 : thickness <= 1.2 ? 3 : thickness <= 1.5 ? 4 : 5; const limits = coilWidth < 500 ? [15, 15, 13, 13, 0, 7] : coilWidth < 1000 ? [16, 16, 13, 13, 0, 7] : [25, 21, 20, 17, 15, 10]; return limits[band] || 0; }
function longitudinalRate(width, mode, coilWidth) { const table = coilWidth < 500 || width < 20 ? PRICE.longitudinal.narrow : PRICE.longitudinal.standard; return table[stripBand(width)]?.[mode] || 0; }
function quantityToTons(quantity, unit, thickness, width, length) { if (unit === 'tons') return quantity; if (unit === 'meters') return quantity * thickness * width * PRICE.density * 0.0000078; return quantity * thickness * (width / 1000) * (length / 1000) * PRICE.density / 1000; }

function serviceData(coilWidth, productWidth, thickness, volume, price, cardSize = '') {
  const laneWidths = Array.isArray(productWidth) ? productWidth : [productWidth], usedWidth = laneWidths.reduce((sum, width) => sum + width, 0), pieces = selectedType === 'rewind' ? 1 : laneWidths.length, scrap = coilWidth - usedWidth, yieldRate = usedWidth / coilWidth;
  if (!pieces || (selectedType !== 'sheet' && selectedType !== 'rewind' && maxStrips(thickness, coilWidth) < pieces) || (selectedType !== 'sheet' && selectedType !== 'rewind' && scrap > 0 && scrap < PRICE.longitudinal.minScrap)) return null;
  const mode = scrap === 0 ? 'full' : 'partial', openCutMode = getRadio('openMode') || 'open', operations = [], hasGrinding = getRadio('surface') === '4n';
  let firstCut = 0;
  let grinding = 0; if (hasGrinding) { grinding = grindingPrice(selectedType, thickness, volume, openCutMode); operations.push({ name: '1. Шлифовка', mode: openCutMode === 'open' ? 'полностью открытый рулон' : openCutMode === 'full' ? 'полностью рулон' : 'частичный рулон', price: grinding }); if (getRadio('film') !== 'none' && getRadio('filmSides') === 'two') { const rewindPrice = PRICE.grinding.rewind[openCutMode]; operations.push({ name: 'Дополнительная перемотка на шлифовке', mode: 'вторая сторона', price: charge(rewindPrice, volume, selectedType === 'sheet' ? 1 : PRICE.grinding.rollMinTons, openCutMode) }); } }
  if (selectedType === 'strip' || selectedType === 'card') { const cutMode = openCutMode, tariffWidth = Math.max(...laneWidths); firstCut = longitudinalRate(tariffWidth, cutMode, coilWidth); if (!firstCut) return null; firstCut = charge(firstCut, volume, PRICE.longitudinal.minTons, cutMode); if ($('specialConditions').checked) firstCut += PRICE.longitudinal.special; if ($('furtherProcessing').checked) firstCut = Math.max(0, firstCut - PRICE.longitudinal.followUpDiscount); operations.push({ name: selectedType === 'card' ? (hasGrinding ? '2. Продольная резка в ленту' : '1. Продольная резка в ленту') : hasGrinding ? '2. Продольная резка в ленту' : '1. Продольная резка в ленту', mode: cutMode === 'open' ? 'открытый рулон до конца' : cutMode === 'full' ? 'полный рулон' : 'частичный рулон', price: firstCut }); }
  if (selectedType === 'rewind') { const tariff = thickness <= .4 ? PRICE.rewind.narrowThin : PRICE.rewind, rewindMode = openCutMode; firstCut = charge(tariff[rewindMode], volume, PRICE.rewind.minTons, rewindMode); if ($('specialConditions').checked) firstCut += PRICE.longitudinal.special; operations.push({ name: hasGrinding ? '2. Перемотка рулона' : '1. Перемотка рулона', mode: rewindMode === 'open' ? 'открытый рулон до конца' : rewindMode === 'full' ? 'полный рулон' : 'частичный рулон', price: firstCut }); }
  let secondCut = 0; if (selectedType === 'sheet' || selectedType === 'card') { const cutMode = openCutMode; secondCut = charge(PRICE.crossCut[cutMode], volume, PRICE.crossCut.minTons, cutMode); if ($('specialConditions').checked) secondCut += PRICE.crossCut.special; if ($('noPallet').checked) secondCut = Math.max(0, secondCut - 500); operations.push({ name: selectedType === 'card' ? '3. Поперечная резка в карточки' : hasGrinding ? '2. Поперечная резка в лист' : '1. Поперечная резка в лист', mode: cutMode === 'open' ? 'открытый рулон до конца' : cutMode === 'full' ? 'полный рулон' : 'частичный рулон', price: secondCut }); } else if ($('noPallet').checked) firstCut = Math.max(0, firstCut - 500);
  const film = filmPrice(selectedType, thickness, yieldRate); if (film) operations.push({ name: 'Плёнка', mode: getRadio('filmSides') === 'two' ? 'с двух сторон' : 'с одной стороны', price: film });
  const materialCost = Number($('materialCost').value), effectiveMaterial = materialCost / yieldRate, scrapCost = materialCost * (1 - yieldRate) / yieldRate, processing = operations.reduce((sum, item) => sum + item.price, 0);
  return { coilWidth, pieces, scrap, yieldRate, price, cardSize, effectiveMaterial, scrapCost, cutting: firstCut + secondCut, firstCut, secondCut, grinding, film, processing, total: price + processing + scrapCost, mode, operations };
}

function cardLayouts(coilWidth, firstWidth, secondWidth, thickness) {
  const layouts = [], max = maxStrips(thickness, coilWidth), duplicate = firstWidth === secondWidth;
  for (let first = 0; first <= max; first += 1) for (let second = 0; second <= max - first; second += 1) {
    if (!first && !second) continue;
    if (duplicate && second) continue;
    const widths = [...Array(first).fill(firstWidth), ...Array(second).fill(secondWidth)], used = widths.reduce((sum, width) => sum + width, 0), scrap = coilWidth - used;
    if (used <= coilWidth && (scrap === 0 || scrap >= PRICE.longitudinal.minScrap)) {
      const label = `${first ? `${first}×${firstWidth} мм` : ''}${first && second ? ' + ' : ''}${second ? `${second}×${secondWidth} мм` : ''}`;
      layouts.push({ widths, label });
    }
  }
  return layouts;
}

function stripLayouts(coilWidth, stripWidth, thickness) {
  const layouts = [], max = Math.min(maxStrips(thickness, coilWidth), Math.floor(coilWidth / stripWidth));
  for (let count = 1; count <= max; count += 1) {
    const used = count * stripWidth, scrap = coilWidth - used;
    if (scrap === 0 || scrap >= PRICE.longitudinal.minScrap) layouts.push({ widths: Array(count).fill(stripWidth), label: `${count}×${decimal(stripWidth)} мм` });
  }
  return layouts;
}
function multiStripLayouts(coilWidth, stripWidths, thickness) { const widths = [...new Set(stripWidths)].sort((a, b) => a - b); if (widths.length <= 1) return stripLayouts(coilWidth, widths[0], thickness); const layouts = [], max = maxStrips(thickness, coilWidth); function build(index, selected, used) { if (index === widths.length) { const scrap = coilWidth - used; if (selected.length && (scrap === 0 || scrap >= PRICE.longitudinal.minScrap)) { const counts = widths.map(width => selected.filter(item => item === width).length).filter(Boolean); const label = widths.map((width, i) => counts[i] ? `${counts[i]}×${width} мм` : '').filter(Boolean).join(' + '); layouts.push({ widths: selected, label }); } return; } const width = widths[index], maxCount = Math.min(max - selected.length, Math.floor((coilWidth - used) / width)); for (let count = 1; count <= maxCount; count += 1) build(index + 1, [...selected, ...Array(count).fill(width)], used + count * width); } build(0, [], 0); return layouts; }

function calculate() {
  const thickness = Number($('thickness').value), productWidthRaw = $('productWidth').value.trim(), stripSizeMode = selectedType === 'strip' ? (getRadio('stripSizeMode') || 'single') : 'single', stripOrders = selectedType === 'strip' && stripSizeMode === 'multiple' ? readStripOrders() : [], productWidths = selectedType === 'strip' && stripSizeMode === 'multiple' ? [...new Set(stripOrders.map(order => order.width))] : [Number(productWidthRaw)], productWidth = productWidths[0], length = Number($('productLength').value) || 0, quantity = Number($('quantity').value), materialCost = Number($('materialCost').value), price = Number($('price').value), unit = getRadio('unit'), error = $('error'), film = getRadio('film'), filmSides = getRadio('filmSides'), validStripOrders = stripSizeMode !== 'multiple' || (stripOrders.length >= 2 && stripOrders.every(order => order.width > 0 && order.quantity > 0));
  if (![thickness, productWidth, materialCost, price].every(Number.isFinite) || thickness <= 0 || productWidth <= 0 || (!validStripOrders) || (stripSizeMode === 'single' && (!Number.isFinite(quantity) || quantity <= 0)) || materialCost < 0 || price < 0 || (selectedType !== 'strip' && selectedType !== 'rewind' && length <= 0) || (filmSides === 'two' && (film === 'none' || thickness > 2))) { error.textContent = filmSides === 'two' && film === 'none' ? 'Для двухсторонней плёнки выберите PE или LPE.' : filmSides === 'two' && thickness > 2 ? 'Плёнка с двух сторон доступна только до толщины 2,0 мм.' : !validStripOrders ? 'Добавьте минимум два типоразмера и укажите ширину с нужным весом или метражом.' : 'Проверьте заполнение параметров.'; error.hidden = false; return; }
  const volume = stripSizeMode === 'multiple' ? stripOrders.reduce((sum, order) => sum + quantityToTons(order.quantity, unit, thickness, order.width, length), 0) : quantityToTons(quantity, unit, thickness, productWidth, length); if (!Number.isFinite(volume) || volume <= 0) { error.textContent = 'Не удалось перевести количество в тонны. Проверьте размеры.'; error.hidden = false; return; } error.hidden = true;
  const candidates = selectedType === 'sheet' || selectedType === 'rewind' ? [productWidth] : COIL_WIDTHS;
  const rows = (selectedType === 'card' ? candidates.flatMap(width => cardLayouts(width, productWidth, length, thickness).map(layout => serviceData(width, layout.widths, thickness, volume, price, layout.label))) : selectedType === 'strip' ? candidates.flatMap(width => multiStripLayouts(width, productWidths, thickness).map(layout => { const row = serviceData(width, layout.widths, thickness, volume, price, layout.label); if (row && stripSizeMode === 'multiple') row.layoutScore = stripLayoutScore(layout, stripOrders); return row; })) : candidates.map(width => serviceData(width, productWidth, thickness, volume, price))).filter(Boolean).sort((a, b) => selectedType === 'strip' && stripSizeMode === 'multiple' ? a.layoutScore - b.layoutScore || a.total - b.total : a.total - b.total).slice(0, 5); if (!rows.length) { error.textContent = 'По условиям прайса подходящего варианта нет: проверьте ширину, толщину, количество полос и откройник.'; error.hidden = false; return; }
  const productLabel = selectedType === 'strip' && stripSizeMode === 'multiple' ? stripOrders.map(order => `${decimal(order.width)} мм — ${decimal(order.quantity)} ${unit === 'tons' ? 'т' : 'м'}`).join('; ') : decimal(productWidth); $('resultCaption').textContent = `${typeNames[selectedType][0].toUpperCase() + typeNames[selectedType].slice(1)}: ${productLabel}${selectedType !== 'strip' && selectedType !== 'rewind' ? ` × ${decimal(length)} мм` : ''} · объём ${decimal(volume)} т`;
  const best = rows[0]; document.querySelector('.table-wrap').hidden = selectedType === 'sheet' || selectedType === 'rewind'; document.querySelectorAll('.scrap-col,.scrap-cell').forEach(el => el.hidden = selectedType === 'sheet' || selectedType === 'rewind'); document.querySelectorAll('.orientation-col,.orientation-cell').forEach(el => el.hidden = selectedType !== 'card'); $('recommendation').innerHTML = `${selectedType === 'sheet' ? 'Лист' : selectedType === 'rewind' ? 'Рулон' : 'Рекомендуемый рулон:'} <strong>${best.coilWidth} мм</strong>${(selectedType === 'card' || selectedType === 'strip') && best.cardSize ? ` · раскрой ${prettyLayout(best.cardSize)}` : ''}<span>Маршрут: ${best.operations.map(item => item.name.replace(/^\d\. /, '')).join(' → ')}</span>`;
  $('resultsBody').innerHTML = rows.map((row, index) => `<tr class="${index === 0 ? 'best' : ''}"><td><strong>${row.coilWidth} мм</strong>${index === 0 ? '<em>лучший</em>' : ''}</td><td class="orientation-cell">${prettyLayout(row.cardSize)}</td><td>${prettyLayout(row.cardSize) || row.pieces}</td><td class="scrap-cell">${decimal(row.scrap)} мм / ${pct((1 - row.yieldRate) * 100)}</td><td>${pct(row.yieldRate * 100)}</td><td><strong>${money(row.total)} руб/тн</strong></td></tr>`).join('');
  const operationLines = best.operations.map(operation => `<div class="subline"><span>${operation.name}${operation.name === 'Плёнка' ? '' : ` <small>(${operation.mode})</small>`}</span><strong>${money(operation.price)} руб/тн</strong></div>`).join(''); $('priceBreakdown').innerHTML = `<h3>Итоговая цена: ${money(best.total)} руб/тн с НДС</h3><div class="price-lines"><div><span>Прайс</span><strong>${money(best.price)} руб/тн</strong></div><div><span>Переработка</span><strong>${money(best.processing)} руб/тн</strong></div>${operationLines}<div><span>Откройник от себестоимости</span><strong>${best.scrapCost ? money(best.scrapCost) + ' руб/тн' : '—'}</strong></div><div class="grand"><span>ИТОГО</span><strong>${money(best.total)} руб/тн</strong></div></div>`;
  $('note').textContent = selectedType === 'card' && getRadio('surface') === '4n' ? 'Карточки: сначала шлифовка, затем продольная резка в ленту и поперечная резка открытого рулона до конца.' : selectedType === 'card' ? 'Карточки: сначала продольная резка в ленту, затем поперечная резка открытого рулона до конца.' : selectedType === 'sheet' && getRadio('surface') === '4n' ? 'Шлифованный лист: сначала шлифовка, затем поперечная резка открытого рулона до конца.' : selectedType === 'rewind' ? 'Рулон рассчитан как отдельная операция перемотки без продольного раскроя.' : 'Автоматически применены условия прайса по режиму рулона, минимальному объёму и дальнейшей переработке.';
  const customMinWidth = selectedType === 'strip' ? productWidths.reduce((sum, width) => sum + width, 0) : productWidth, customProductWidth = selectedType === 'strip' && productWidths.length > 1 ? productWidths : productWidth; const custom = document.createElement('tr'); custom.className = 'custom-row'; custom.innerHTML = `<td><input id="customCoilWidth" type="number" min="${customMinWidth}" step="1" placeholder="Своя ширина"></td><td class="orientation-cell"${selectedType === 'card' ? '' : ' hidden'}>${selectedType === 'card' ? 'Ориентация задаётся в таблице' : ''}</td><td colspan="${selectedType === 'sheet' || selectedType === 'rewind' ? 3 : 4}" id="customResult">Введите ширину — расчёт появится автоматически</td>`; $('resultsBody').appendChild(custom); $('customCoilWidth').addEventListener('input', () => renderCustom(Number($('customCoilWidth').value), thickness, customProductWidth, volume, price));
  localStorage.setItem('metal-cutter-values', JSON.stringify({ type: selectedType, thickness, productWidth: productWidthRaw, stripSizeMode, stripOrders, length, quantity, unit, volume, materialCost, price, surface: getRadio('surface'), film, filmSides, openMode: getRadio('openMode'), special: $('specialConditions').checked, further: $('furtherProcessing').checked, noPallet: $('noPallet').checked }));
}
function renderCustom(coilWidth, thickness, productWidth, volume, price) { const out = $('customResult'), widths = Array.isArray(productWidth) ? productWidth : [productWidth], minWidth = widths.reduce((sum, width) => sum + width, 0); if (!coilWidth || coilWidth < minWidth) { out.textContent = 'Введите ширину не меньше суммы типоразмеров'; return; } const layouts = selectedType === 'strip' ? multiStripLayouts(coilWidth, widths, thickness) : [], layout = layouts.at(-1), row = serviceData(coilWidth, layout ? layout.widths : productWidth, thickness, volume, price, layout?.label || ''); if (!row) { out.textContent = 'Вариант не проходит по условиям прайса или минимальному откройнику'; return; } out.innerHTML = `${decimal(coilWidth)} мм · ${prettyLayout(row.cardSize) || row.pieces} полос / листов${selectedType === 'sheet' || selectedType === 'rewind' ? '' : ` · откройник <strong>${decimal(row.scrap)} мм</strong>`} · переработка ${money(row.processing)} руб/тн · откройник от себестоимости ${money(row.scrapCost)} руб/тн · <strong>${money(row.total)} руб/тн</strong>`; }
document.querySelectorAll('.type-card').forEach(card => card.addEventListener('click', () => setType(card.dataset.type))); $('nextButton').addEventListener('click', () => showStep(2)); $('backButton').addEventListener('click', () => showStep(1)); $('calculateButton').addEventListener('click', () => { calculate(); if (!$('error').hidden) return; showStep(3); }); $('editButton').addEventListener('click', () => showStep(2)); $('resetButton').addEventListener('click', () => { localStorage.removeItem('metal-cutter-values'); location.reload(); });
try { const saved = JSON.parse(localStorage.getItem('metal-cutter-values') || 'null'); if (saved) { setType(saved.type || 'strip'); ['thickness', 'productWidth', 'productLength', 'quantity', 'materialCost', 'price'].forEach(id => { if (saved[id] !== undefined) $(id).value = saved[id]; }); document.querySelector(`input[name="stripSizeMode"][value="${saved.stripSizeMode || 'single'}"]`)?.click(); if (saved.stripSizeMode === 'multiple' && Array.isArray(saved.stripOrders)) { const rows = document.querySelector('.multi-strip-rows'); if (rows) { rows.innerHTML = ''; saved.stripOrders.forEach(order => addStripOrderRow(rows, order.width, order.quantity)); } } document.querySelector(`input[name="unit"][value="${saved.unit}"]`)?.click(); document.querySelector(`input[name="surface"][value="${saved.surface}"]`)?.click(); document.querySelector(`input[name="film"][value="${saved.film}"]`)?.click(); document.querySelector(`input[name="filmSides"][value="${saved.filmSides}"]`)?.click(); document.querySelector(`input[name="openMode"][value="${saved.openMode || 'partial'}"]`)?.click(); $('specialConditions').checked = false; $('furtherProcessing').checked = false; $('noPallet').checked = false; } } catch {} setType(selectedType); showStep(1);
document.querySelectorAll('input[name="film"]').forEach(input => input.addEventListener('change', () => { if (input.checked && input.value === 'none') document.querySelector('input[name="filmSides"][value="one"]').checked = true; })); if (getRadio('film') === 'none') document.querySelector('input[name="filmSides"][value="one"]').checked = true;
['specialConditions', 'furtherProcessing', 'noPallet'].forEach(id => { if ($(id)) $(id).checked = false; });
document.querySelector('input[name="unit"][value="tons"]').checked = true; document.querySelector('input[name="surface"][value="none"]').checked = true; document.querySelector('input[name="film"][value="none"]').checked = true; document.querySelector('input[name="filmSides"][value="one"]').checked = true; document.querySelector('input[name="openMode"][value="partial"]').checked = true;
document.querySelectorAll('label').forEach(label => { if (label.textContent.trim() === '4N') label.lastChild.textContent = ' Шлифовка'; });
